apiVersion: v1
kind: Service
metadata:
  name: sorack
  namespace: sorack
spec:
  type: ClusterIP
  selector:
    app: sorack
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
